Models/Office/ViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RobotJester.Models
{
    

    public class ViewProduct //Used for creating and updating a current product
    {
        [Display(Name="Product Name")]
        [Required]
        [MinLength(2)]
        public string name {get;set;}
        
        [Display(Name="Price")]
        [Required]
        public float price {get;set;}
        
        [Display(Name="Description")]
        [Required]
        [MinLength(5)]
        public string description {get;set;}

        [Display(Name="Starting Quantity")]
        [Required]
        public int instock_quantity { get; set;}
        // [Display(Name="Product Weight")]
        
        [Display(Name="Weight")]
        [Required]
        public float weight { get; set; }

        [Display(Name="Image URL")]
        public string image_url { get; set; }
        
        [Display(Name="X-Axis-Dimension")]
        [Required]
        public float x_dimension { get; set; }
        
        [Display(Name="Y-Axis-Dimension")]
        [Required]
        public float y_dimension { get; set; }
        
        [Display(Name="Z-Axis-Dimension")]
        [Required]
        public float z_dimension { get; set; }
    }
    
}

Controllers/OfficeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RobotJester.Models;
using Microsoft.EntityFrameworkCore;

namespace RobotJester.Controllers
{
    /*
    This is the OfficeController, here is where someone with admin privledges will be 
    redirected upon login. This is where you can manage the store settings like adding 
    more items looking at orders and so on.
     */
    
    public class OfficeController : Controller
    {
        private StoreContext _context;
 
        public OfficeController(StoreContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("Admin/Toolbox")]
        public IActionResult ToolTable()
        {
            return View();        
        }

        //C.R.U.D For inventory management
        [HttpGet]
        [Route("Inventory")]
        public IActionResult Inventory()
        {
            var all = _context.products.ToList();
            ViewBag.Products = all;
            return View();
        }
        
        // Validate product
        [HttpPost]
        [Route("Inventory")]
        public IActionResult Validate(ViewProduct newProduct)
        {
            var all = _context.products.ToList();
            ViewBag.Products = all;
            if(ModelState.IsValid)
            {
                Products product = new Products
                {
                    name = newProduct.name,
                    price = newProduct.price, 
                    description = newProduct.description,
                    instock_quantity = newProduct.instock_quantity,
                    weight = newProduct.weight,
                    image_url = newProduct.image_url,
                    x_dimension = newProduct.x_dimension,
                    y_dimension = newProduct.y_dimension,
                    z_dimension = newProduct.z_dimension,
                    created_at = DateTime.Now,
                    updated_at = DateTime.Now,
                };
                _context.products.Add(product);
                _context.SaveChanges();
                return RedirectToAction("Inventory");
            }

            return View("Inventory", newProduct);
            
        }


        [HttpGet]
        [Route("Edit/{id}")]
        public IActionResult EditItem(int id)
        {
            Products edit = _context.products.SingleOrDefault(item => item.product_id == id);
            return View(edit);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        public IActionResult ValidateEdit(int id, ViewProduct edit)
        {
            var all = _context.products.ToList();
            ViewBag.Products = all;
            if(ModelState.IsValid)
            {
                Products current_product = _context.products.SingleOrDefault(p => p.product_id==id);
                {
                    current_product.name = edit.name;
                    current_product.price = edit.price; 
                    current_product.description = edit.description;
                    current_product.instock_quantity = edit.instock_quantity;
                    current_product.weight = edit.weight;
                    current_product.image_url = edit.image_url;
                    current_product.x_dimension = edit.x_dimension;
                    current_product.y_dimension = edit.y_dimension;
                    current_product.z_dimension = edit.z_dimension;
                    current_product.updated_at = DateTime.Now;
                    _context.SaveChanges();
                };
                return RedirectToAction("Inventory");
            }
            return View("Inventory", edit);
        }

        //Delete a specific item
        [HttpGet]
        [Route("Delete/Product/{id}")]
        public IActionResult DeleteItem(int id)
        {
            Products item_to_be_removed = _context.products.SingleOrDefault(i => i.product_id == id);
            if(item_to_be_removed == null)
            {
                return RedirectToAction("Inventory");
            }

            List<Cart_Items> remove_from_user = _context.cart_items.Where(p => p.product_id==item_to_be_removed.product_id).ToList();
            foreach(var r in remove_from_user)
            {
                //Remove the product from the cart of users who have it added to their cart
                _context.Remove(r);
                _context.SaveChanges();
            }
            _context.Remove(item_to_be_removed);
            _context.SaveChanges();
            return RedirectToAction("Inventory");
        }


        //C.R.U.D For orders
        [HttpGet]
        [Route("Orders/All")]
        public IActionResult Orders()
        {
            List<Orders> order_list = _context.orders.Include(c => c.customer).ToList();
            return View(order_list);
        }   

        // View specific order with a customer
        [HttpGet]
        [Route("Orders/Show/{id}")]
        public IActionResult ShowOrder(int id)
        {
            var specific = _context.orders.Include(a => a.customer).Include(a => a.customer_address).SingleOrDefault(o => o.order_id==id);
            List<Cart_Items> ordered_items = _context.cart_items.Include(i => i.all_items).Where(a => a.order_id==id && a.is_active==0).ToList();
            ViewBag.Order = ordered_items;
            return View(specific);
        }

        //C.R.U.D For user's
        [HttpGet]
        [Route("Users")]
        public IActionResult Users()
        {
            return View();
        }

        [HttpGet]
        [Route("Users/Show/{id}")]
        public IActionResult UserList(int id)
        {
            return null;
        }




        
    }
}

Controllers/OrderController.cs
/*TODO: RENAME TO OFFICE CONTROLLER THIS IS WHERE
ONLY ADMINS AND MANAGERS CAN VIEW ORDERS AND OTHER
SENSITIVE DATA */

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RobotJester.Models;
using Microsoft.EntityFrameworkCore;

namespace RobotJester.Controllers
{
    
    public class OfficeController : Controller
    {
        private StoreContext _context;
 
        public OfficeController(StoreContext context)
        {
            _context = context;
        }
            

        

        [HttpGet]
        [Route("Orders")]
        public IActionResult Orders()
        {
            return View();
        }   

        [HttpGet]
        [Route("Orders/{id}")]
        public IActionResult Show()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddToCart()
        {
            Orders cart = new Orders
            {
            };
            return RedirectToAction("orders/@product_id"); 
        }
    }
}

Views/Office/Create.cshtml
@model RobotJester.Models.ViewProduct

<form method="post" asp-controller="Office" asp-action="Validate">
    <div class="form-group row">
        <div class="col-sm-6">
            <span asp-validation-for="name"></span>
            <label asp-for="name">Product Name</label>
            <input class="form-control" asp-for="name">
        </div>
        <div class="col-sm-6">
            <span asp-validation-for="price"></span>
            <label asp-for="price">Price</label>
            <input class="form-control" asp-for="price">
        </div>
        <div class="col-sm-12">
            <span asp-validation-for="description"></span>
            <label asp-for="description">Description</label>         
            <textarea rows="3" class="form-control" asp-for="description"></textarea>
        </div>
        <div class="col-sm-6">
            <span asp-validation-for="instock_quantity"></span>
            <label asp-for="instock_quantity">Quantity Instock</label>
            <input class="form-control" asp-for="instock_quantity">
        </div>
        <div class="col-sm-6">
            <span asp-validation-for="weight"></span>
            <label asp-for="weight">Weight</label>
            <input class="form-control" asp-for="weight">
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <span asp-validation-for="x_dimension"></span>
                <label asp-for="x_dimension">X-Axis-Dimension</label>
                <input class="form-control" asp-for="x_dimension">
            </div>
            <div class="form-group">
                <span asp-validation-for="y_dimension"></span>
                <label asp-for="y_dimension">Y-Axis-Dimension</label>
                <input class="form-control" asp-for="y_dimension">
            </div>
            <div class="form-group">
                <span asp-validation-for="z_dimension"></span>
                <label asp-for="z_dimension">Z-Axis-Dimension</label>
                <input class="form-control" asp-for="z_dimension">
            </div>
        </div>
        <div class="col-sm-6">
            <img src="https://i.stack.imgur.com/mg50D.png"alt="">
        </div>        
    <div class="col-sm-12">
        <input type="submit" value="Create" class="btn btn-success">
    </div>
</form>

Views/Office/Edit.cshtml
<div class="row">
    <table class="table table-hover table-bordered table-responsive">
        <thead>
            <tr>
                <th><span class="glyphicon glyphicon-wrench"></span> Product Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Created On</th>
                <th>Updated On</th>
                <th>Action(s)</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in ViewBag.Products)
            {
            <tr>
                <td>@item.name</td>
                <td>@item.instock_quantity</td>
                <td>$@item.price</td>
                <td>@item.created_at.ToString("D")</td>
                <td>@item.updated_at.ToString("D")</td>
                <td><a href="/edit/@item.product_id"><span class="glyphicon glyphicon-pencil"></span> Edit</a> | <a asp-action="Delete"><span class="glyphicon glyphicon-trash"></span> Delete</a></td>
            </tr>
            }
        </tbody>
    </table>
    </div>

Views/Office/EditItem.cshtml
@model Products
@using RobotJester.Models

<div class="container form-other">
    <h2 class="text-center">Update the record of an existing product</h2>
    <form asp-controller="Office" asp-action="ValidateEdit" method="POST">
        <div class="col-sm-6">
            <span asp-validation-for="name"></span>
            <label asp-for="name">Product Name</label>
            <input class="form-control" asp-for="name" >
        </div>
        <div class="col-sm-6">
            <span asp-validation-for="price"></span>
            <label asp-for="price">Price</label>
            <input class="form-control" asp-for="price">
        </div>
        <div class="col-sm-12">
            <span asp-validation-for="description"></span>
            <label asp-for="description">Description</label>         
            <textarea rows="3" class="form-control" asp-for="description"></textarea>
        </div>
        <div class="col-sm-4">
            <span asp-validation-for="instock_quantity"></span>
            <label asp-for="instock_quantity">Quantity Instock</label>
            <input class="form-control" asp-for="instock_quantity">
        </div>
        <div class="col-sm-4">
            <span asp-validation-for="weight"></span>
            <label asp-for="weight">Weight</label>
            <input class="form-control" asp-for="weight">
        </div>
        <div class="col-sm-4">
            <span asp-validation-for="image_url"></span>
            <label asp-for="image_url">Product Image URL</label>
            <input placeholder="https://" class="form-control" asp-for="image_url">
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <span asp-validation-for="x_dimension"></span>
                <label asp-for="x_dimension">X-Axis-Dimension (in inches)</label>
                <input class="form-control" asp-for="x_dimension">
            </div>
            <div class="form-group">
                <span asp-validation-for="y_dimension"></span>
                <label asp-for="y_dimension">Y-Axis-Dimension (in inches)</label>
                <input class="form-control" asp-for="y_dimension">
            </div>
            <div class="form-group">
                <span asp-validation-for="z_dimension"></span>
                <label asp-for="z_dimension">Z-Axis-Dimension (in inches)</label>
                <input class="form-control" asp-for="z_dimension">
            </div>
        </div>
        <div class="col-sm-6">
            <img src="https://i.stack.imgur.com/mg50D.png"alt="">
        </div>        
        <div class="col-sm-12 text-center">
            <input type="submit" value="Update" class="btn btn-primary">
        </div>
    </form>
</div>

Views/Office/Inventory.cshtml
@model RobotJester.Models.ViewProduct
@using RobotJester.Models

<div class="container form-other">
    <h2>Add new product</h2>
    <form method="post" asp-controller="Office" asp-action="Validate">
        <div class="form-group row">
            <div class="col-sm-6">
                <span asp-validation-for="name"></span>
                <label asp-for="name">Product Name</label>
                <input class="form-control" asp-for="name">
            </div>
            <div class="col-sm-6">
                <span asp-validation-for="price"></span>
                <label asp-for="price">Price</label>
                <input placeholder="$" class="form-control" asp-for="price">
            </div>
            <div class="col-sm-12">
                <span asp-validation-for="description"></span>
                <label asp-for="description">Description</label>         
                <textarea rows="3" class="form-control" asp-for="description"></textarea>
            </div>
            <div class="col-sm-4">
                <span asp-validation-for="instock_quantity"></span>
                <label asp-for="instock_quantity">Quantity Instock</label>
                <input class="form-control" asp-for="instock_quantity">
            </div>
            <div class="col-sm-4">
                <span asp-validation-for="weight"></span>
                <label asp-for="weight">Weight</label>
                <input placeholder="ex. 2.5lb" class="form-control" asp-for="weight">
            </div>
            <div class="col-sm-4">
                <span asp-validation-for="image_url"></span>
                <label asp-for="image_url">Product Image URL</label>
                <input placeholder="https://" class="form-control" asp-for="image_url">
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <span asp-validation-for="x_dimension"></span>
                    <label asp-for="x_dimension">X-Axis-Dimension (in inches)</label>
                    <input placeholder="ex. 0.5in" class="form-control" asp-for="x_dimension">
                </div>
                <div class="form-group">
                    <span asp-validation-for="y_dimension"></span>
                    <label asp-for="y_dimension">Y-Axis-Dimension (in inches)</label>
                    <input placeholder="ex. 0.5in" class="form-control" asp-for="y_dimension">
                </div>
                <div class="form-group">
                    <span asp-validation-for="z_dimension"></span>
                    <label asp-for="z_dimension">Z-Axis-Dimension (in inches)</label>
                    <input placeholder="ex. 0.5in" class="form-control" asp-for="z_dimension">
                </div>
            </div>
            <div class="col-sm-6">
                <img class="img-responsive" src="https://i.stack.imgur.com/mg50D.png"alt="">
            </div>        
        <div class="col-sm-12 text-center">
            <input type="submit" value="Create" class="btn btn-primary">
        </div>
    </form>
</div>
<div class="">
    @Html.Partial("Partials/EditTable")
</div>

Views/Office/Orders.cshtml
@model List<Orders>
@using RobotJester.Models
<div class="container">
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Order #</th>
                <th>Customer</th>
                <th>Order Date</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var o in @Model)
            {
                <tr>
                    <td><a href="Show/@o.order_id">Order #@o.order_id</a></td>
                    <td><a href="">@o.customer.first_name @o.customer.last_name</a></td>
                    <td>@o.created_at.ToString("D")</td>
                    <td>$@o.total_billed</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Office/ShowOrder.cshtml
@model Orders
<div class="container">
    <div class="row">
        <div class="col-xs-12">
    		<div class="">
    			<h2 class="text-left">Order Invoice</h2>
    		</div>
    		<hr>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    					<strong>Billed To:</strong><br>
    					@Model.customer.first_name @Model.customer.last_name<br>
						@Model.customer_address.address_line_one<br>
						@if(Model.customer_address.address_line_two == null)
						{
							//Blank if no second address line
						}
						else
						{
							@Model.customer_address.address_line_two<br>
						}
						@Model.customer_address.city, @Model.customer_address.state_or_province @Model.customer_address.zip_or_postal<br>
						@Model.customer_address.country
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
    					<strong>Billed To:</strong><br>
    					@Model.customer.first_name @Model.customer.last_name<br>
						@Model.customer_address.address_line_one<br>
						@if(Model.customer_address.address_line_two == null)
						{
							//Blank if no second address line
						}
						else
						{
							@Model.customer_address.address_line_two<br>
						}
						@Model.customer_address.city, @Model.customer_address.state_or_province @Model.customer_address.zip_or_postal<br>
						@Model.customer_address.country
    				</address>
    			</div>
    		</div>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    					<strong>Details:</strong><br>
    					Email: @Model.customer.email<br>
                        Phone: @Model.customer.phone<br>
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
    					<strong>Order Date:</strong><br>
    					@Model.created_at.ToString("D")<br>
    				</address>
    			</div>
    		</div>
    	</div>
    </div>
    
    <div class="row">
    	<div class="col-md-12">
    		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h3 class="panel-title"><strong>Order summary</strong></h3>
    			</div>
    			<div class="panel-body">
    				<div class="table-responsive">
    					<table class="table table-condensed table-striped">
    						<thead>
                                <tr>
        							<td><strong>Item</strong></td>
        							<td class="text-center"><strong>Price</strong></td>
        							<td class="text-center"><strong>Quantity</strong></td>
        							<td class="text-right"><strong>Totals</strong></td>
                                </tr>
    						</thead>
    						<tbody>
    							<!-- foreach here with ViewBag -->
                                @foreach(var i in ViewBag.Order)
                                {
                                    var tempTotal = @i.all_items.price * @i.quantity;
                                    <tr>
                                        <td>@i.all_items.name</td>
                                        <td class="text-center">@i.all_items.price.ToString("C")</td>
                                        <td class="text-center">@i.quantity</td>
                                        <td class="text-right">@tempTotal.ToString("C")</td>
    							    </tr>
                                }
    							<tr>
    								<td class="thick-line"></td>
    								<td class="thick-line"></td>
    								<td class="thick-line text-center"><strong>Subtotal</strong></td>
    								<td class="thick-line text-right">@Model.subtotal.ToString("C")</td>
    							</tr>
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Shipping</strong></td>
    								<td class="no-line text-right">@Model.tax.ToString("C")</td>
    							</tr>
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Total</strong></td>
    								<td class="no-line text-right">@Model.total_billed.ToString("C")</td>
    							</tr>
    						</tbody>
    					</table>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>

Views/Office/ToolTable.cshtml
<div class="container">
    <div class="row">
        <h2 class="text-center">Administrator Toolbox</h2>
        <table class="table table-hover table-bordered table-responsive">
            <thead>
                <tr>
                    <th><span class="glyphicon glyphicon-wrench"></span> Tools</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><span class="glyphicon glyphicon-barcode"></span><a href="/Inventory"> Inventory Management</a></td>
                    <td>Keep track of your store stock</td>
                </tr>
                <tr>
                    <td><span class="glyphicon glyphicon-book"></span><a asp-action="Orders" asp-controller="Office"> Order History</a></td>
                    <td>Detailed list of all your orders,</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>